### ISSUE TITLE
Progress + Collaboration?

### ISSUE THREAD

**Issue by AnalogJ** [halprin/fhirpath#25]
Hey @halprin 
I'm a big fan of this work. I'm building an open source PHR called [Fasten Health](https://github.com/fastenhealth/fasten-onprem) that's also written in Go, and I had do a number of unsavory things to extract data from FHIR Resources, including running `fhirpath.js` in a [Goja JS VM](github.com/dop251/goja).

I'd love to migrate to a Go native version of FhirPath, and I'd love to assist/collaborate if you're open to it. 

Your README says that "5 out of the 686 [official tests](https://hl7.org/fhirpath/tests.html) pass.", but it hasn't been updated in a couple of months. Is that still accurate?

**Comment by halprin** [comment]
Hey! I'm on vacation through Monday, so let me get back to you afterwards. I'm intrigued!

**Comment by halprin** [comment]
Hello there @AnalogJ.  Wow, that's quite a way to get FHIR path working!

I'm up to 35 of the official tests passing, but obviously I still have a long way to go.  I also have a `polymorphism` branch where I'm working on support when fields have different datatypes and the FHIR path doesn't need to specify (e.g. `Patient.deceased`).  This is a hobby project of mine, and because my full time software engineering job is currently... a little hectic, it seems to sap me of wanting to work on this FHIR project.

With that said, I'm still passionate about working and completing this project.  I'd love to collaborate on this.  I'd love to show you around the code base, get your feedback, and talk next steps on having you collaborate.

**Comment by AnalogJ** [comment]
Hey @halprin - haha, I did say it was a pretty unsavory solution. 

I definitely understand how difficult it can be to find time to work on an open-source side-project when you have a busy dayjob, part of the reason why I quit to work on Fasten fulltime :)

Here's my calendly link - https://calendly.com/jason-kulatunga/
If you have time, I'd love to jump on a call!

**Comment by halprin** [comment]
As discussed in the meeting a while ago and today...

- We are open for collaboration.
- Made you a collaborator on this repository.
- I'll generate some issues and assign them to you.
